spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YOzyazici/E-Commerce.git
  profiles:
    active: dev
server:
  port: 8050